apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-postgresql
spec:
  capacity:
    storage: 1Gi  # Adjust size as necessary
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  # This is an example configuration for a local volume; you may need to adjust this based on your infrastructure.
  local:
    path: /var/data/db-postgresql
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - db-postgresql-0
